### ISSUE TITLE
There is no verify for nuget.4.6.0

### ISSUE THREAD

**Issue by AlexanderMalyshev** [NuGet/docs.microsoft.com-nuget#1538]
Please see subj:
...\opensource\nuget.4.6.0\nuget.exe verify
Unknown command: 'verify'
NuGet.CommandLine.CommandLineException: Unknown command: 'verify'
   at NuGet.CommandLine.CommandManager.GetCommand(String commandName)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef24999-7e5d-8ba6-a94a-44731aea2a03
* Version Independent ID: 2ba314fb-8315-10d7-47e7-f16bcef48d91
* Content: [NuGet CLI verify command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-verify#feedback)
* Content Source: [docs/tools/cli-ref-verify.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-verify.md)
* Product: **nuget**
* GitHub Login: @dtivel
* Microsoft Alias: **dtivel**

**Comment by dtivel** [comment]
I don't know anything about ...\opensource\nuget.4.6.0\nuget.exe.  What is the full version from running nuget.exe without any arguments?

[Here](https://dist.nuget.org/win-x86-commandline/v4.6.0/nuget.exe) is the official NuGet 4.6.0 CLI.  If I execute nuget.exe with no arguments it outputs:

    NuGet Version: 4.6.0.4971

This version does have the `verify` command.  You'll see it at the bottom of the same output.

Can you try with this version?

Ultimately, I recommend you use the latest version because many bugs have been fixed since 4.6.0.

**Comment by karann-msft** [comment]
@AlexanderMalyshev please reopen the issue if Damon's suggestion didn't resolve your issue.
